import {makeActionCreator} from 'services/utils/actions'

export const RESET = 'analytics/reset'
export const FETCH_TABLE = 'analytics/fetchTable'
export const FETCH_DELTA = 'analytics/fetchDelta'
export const FETCH_ROWS = 'analytics/fetchRows'
export const TOGGLE_ROW = 'analytics/toggleRow'
export const SELECT_ROWS = 'analytics/selectRows'
export const SELECT_TABLE = 'analytics/selectTable'
export const CHANGE_FILTER = 'analytics/changeFilter'
export const TOGGLE_SORTING = 'analytics/toggleSorting'
export const FETCH_VALUES = 'analytics/fetchValues'
export const SELECT_VALUE = 'analytics/selectValue'
export const SEARCH_VALUE = 'analytics/searchValue'
export const REMOVE_VALUE = 'analytics/removeValue'
export const RESET_FILTERS = 'analytics/resetFilters'
export const TOGGLE_DROPDOWN = 'analytics/toggleDropdown'
export const OPEN_POPUP = 'analytics/openPopup'
export const CLOSE_POPUP = 'analytics/closePopup'
export const FETCH_BIDS_HISTORY = 'analytics/fetchBidsHistory'
export const CHANGE_BID = 'analytics/changeBid'
export const TOGGLE_AD = 'analytics/toggleAd'
export const FETCH_SOURCES = 'analytics/fetchSources'
export const TOGGLE_SOURCE = 'analytics/toggleSource'
export const UPDATE_SEARCH = 'analytics/updateSearch'
export const TOGGLE_SEARCH = 'analytics/toggleSearch'
export const APPLY_SEARCH = 'analytics/applySearch'

export const reset = makeActionCreator(RESET)
export const fetchTable = makeActionCreator(FETCH_TABLE)
export const fetchDelta = makeActionCreator(FETCH_DELTA)
export const fetchRows = makeActionCreator(FETCH_ROWS)
export const toggleRow = makeActionCreator(TOGGLE_ROW)
export const selectTable = makeActionCreator(SELECT_TABLE)
export const changeFilter = makeActionCreator(CHANGE_FILTER, ['name', 'value'])
export const toggleSorting = makeActionCreator(TOGGLE_SORTING)
export const fetchValues = makeActionCreator(FETCH_VALUES)
export const selectValue = makeActionCreator(SELECT_VALUE, ['id', 'value'])
export const searchValue = makeActionCreator(SEARCH_VALUE, ['id', 'value'])
export const removeValue = makeActionCreator(REMOVE_VALUE, ['id', 'value'])
export const resetFilters = makeActionCreator(RESET_FILTERS)
export const toggleDropdown = makeActionCreator(TOGGLE_DROPDOWN)
export const openPopup = makeActionCreator(OPEN_POPUP)
export const closePopup = makeActionCreator(CLOSE_POPUP)
export const fetchBidsHistory = makeActionCreator(FETCH_BIDS_HISTORY)
export const changeBid = makeActionCreator(CHANGE_BID)
export const toggleAd = makeActionCreator(TOGGLE_AD)
export const fetchSources = makeActionCreator(FETCH_SOURCES)
export const toggleSource = makeActionCreator(TOGGLE_SOURCE)
export const updateSearch = makeActionCreator(UPDATE_SEARCH)
export const toggleSearch = makeActionCreator(TOGGLE_SEARCH)
export const applySearch = makeActionCreator(APPLY_SEARCH)
export const selectRows = makeActionCreator(SELECT_ROWS)
